### ISSUE TITLE
Why do we use native modules instead of spawning the processes?

### ISSUE THREAD

**Issue by IonicaBizau** [davidmarkclements/screenres#8] opened 2015-10-11 11:18 UTC
Spawning the processes would be much easier in terms of maintaining.

**Comment by davidmarkclements** [comment] 2015-10-11 13:10
for linux we could certainly just spawn the process 
for os x there is no `xrandr` equivalent that comes bundled with OS X and I'd rather not have separately installable dependencies

initially this was just for OS X and was intended as a small learning project (I'm not (yet) a C++ guy either!)

I think originally I stayed in C-land because I wanted in future to change screen res via direct C apis instead of via `xrandr` so that even `xrandr` was no longer a hard dependency

feel free to update to simply spawning xrandr for rc1 branch

**Comment by IonicaBizau** [comment] 2015-10-11 13:12
We could simply check the platform using the `os` module and then run the correct command, right?

**Comment by davidmarkclements** [comment] 2015-10-11 13:15
well sort of

the correct command for linux yes

as far as I know there is no command for os x  -  so then we'd also need to tweak it to build natively on os x

**Comment by davidmarkclements** [comment] 2018-02-19 03:01
closing as I'm happy to keep native build – this is a nice cross platform solution

**Closed as completed by davidmarkclements** 2018-02-19 03:01 UTC
